spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1073177275725-9ausl0fbfdi4bpd053tpqesn6qoaktou.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "<http://localhost:3000/login/oauth2/code/google>"
          kakao:
            client-id: ENC(1HIZn2QzKn4nRunWgWlDbmi6D948IfN/0vuLeoPwwc8oJxlsWOfoU7/K3pOUWG4v)   # REST API 키
            client-secret: ENC(w/Ip7Zu91manw2kqhhRPO6St73p2GOaOhtigoc+qT4pNbH+FKvuALyd7cq9nv1Zt)
            redirect-uri: "<https://66challenge-server.store/login/oauth2/code/kakao>"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email, gender, age_range  # 동의 항목
            client-name: Kakao
            naver:
              client-id: ENC(FuYscwF2S65D3gZ1dFQP2VNW6gd5ZxGs5yqltpIvHTw=)   # REST API 키
              client-secret: ENC(35dAwGDL/QoXHR0wUz7dxtlrjk6qk8Bq)
              redirect-uri: "<https://66challenge-server.store/login/oauth2/code/naver>"
              authorization-grant-type: authorization_code
              scope: name, email, profile_image, gender, age  # 동의 항목
              client-name: Naver
          provider:
            kakao:
              authorization-uri: <https://kauth.kakao.com/oauth/authorize>
              token-uri: <https://kauth.kakao.com/oauth/token>
              user-info-uri: <https://kapi.kakao.com/v2/user/me>
              user-name-attribute: id
            naver:
              authorization_uri: <https://nid.naver.com/oauth2.0/authorize>
              token_uri: <https://nid.naver.com/oauth2.0/token>
              user-info-uri: <https://openapi.naver.com/v1/nid/me>
              user_name_attribute: response